-- MySQL Script generated by MySQL Workbench
-- Sun Dec 30 21:42:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema medical4
-- -----------------------------------------------------
DROP SCHEMA medical4;
CREATE SCHEMA IF NOT EXISTS medical4 DEFAULT CHARACTER SET utf8 ;
USE medical4;

 
CREATE TABLE treatment (
    treatment_id INT PRIMARY KEY,
    name VARCHAR(255)
)  ENGINE=INNODB;
 
CREATE TABLE itemType (
    item_id INT PRIMARY KEY,
    name VARCHAR(255),
    defaultSpec VARCHAR(255)
)  ENGINE=INNODB;


CREATE TABLE service (
    ID INT(255) PRIMARY KEY,
    itemTypeID INT(255),
    treatmentID INT(255),
    spec VARCHAR(255),
    datedone DATE,
    dateout DATE,
    remarks VARCHAR(255),
    price DECIMAL, 
    CONSTRAINT `fk_itemtype`
    FOREIGN KEY (`itemTypeID`)
        REFERENCES `itemtype` (`item_id`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_treatment`
    FOREIGN KEY (`treatmentID`)
        REFERENCES `treatment` (`treatment_id`) 
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;


CREATE TABLE serviceprice (
    ID INT(255) PRIMARY KEY,
    itemTypeID INT(255),
    treatmentID INT(255),
    price DECIMAL,
    CONSTRAINT `fk_itemtype1`
    FOREIGN KEY (`itemTypeID`)
        REFERENCES `itemtype` (`item_id`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_treatment1` 
    FOREIGN KEY (`treatmentID`)
        REFERENCES `treatment` (`treatment_id`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
)  ENGINE=INNODB;

SET FOREIGN_KEY_CHECKS=OFF;

SET FOREIGN_KEY_CHECKS=ON;

